### ISSUE TITLE
add additional parameter from header comment

### ISSUE THREAD

**Issue by steveskrip** [LimnoTech/IWN-Ingest#10]

**Comment by steveskrip** [comment]
@tslawecki Not sure what we need to do with the "Sequence" column in the station metadata header that was suggested to be added.

**Comment by tslawecki** [comment]
Poor issue - I'm looking for an additional command-line parameter per comment

**Comment by tslawecki** [comment]
I had added the following header to a copy of the code on my computer:

  # ==============================================================================
#
# IWN-ingest.py: Interoperable Watershed Network 52 North SOS Ingester
# 
# Usage: IWN-ingest.py datafilename.csv stationconf.json [skipcheck]
#
#   datafilename.csv - contains observation data in CSV format
#   stationconf.json - contains data configuration and station ID in JSON format
#   skipcheck        - if specified, no check is performed for existing data 
#
# Authored by Steve Skripnik and Tad Slawecki, LimnoTech
#
# Developed for US EPA Office of Water under subcontract 
#
#
# ==============================================================================

but then missed posting it.

**Comment by steveskrip** [comment]
Thanks Tad. I'm still a little confused about "no check is performed on existing data". Were you thinking an option that only gathers the GetCapabilities/offering data from the server and doesn't push any data to the server? Or does everything except push data? Or push data without checking to see if it already exists on the server? Sorry if I'm way off base - just want to make sure I'm covering what you're thinking.

**Comment by tslawecki** [comment]
This is what happens when you're not inside my head!

"nocheck" = no check for existing data before pushing to allow (careful) insertion of data into missing gaps.

**Comment by steveskrip** [comment]
added usage flag "-s" or "--skipcheck" that can be placed anywhere in the command. Invokes "Skip date check mode." When used, all data will be pushed to the server regardless of the date, and even data that potentially has already been pushed to the server will be pushed. Used to fill in gaps in data. Should be used carefully. No warning before pushing data.

In practice, the server rejects duplicate data, so there is some safety built into the option.
